/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Legacy Marketing Campaigns Campaigns API
 * The Twilio SendGrid Legacy Marketing Campaigns Campaigns API allows you to manage your marketing email messages programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns to manage your marketing messages with SendGrid [Single Sends](https://docs.sendgrid.com/api-reference/single-sends/) and [Automations](https://docs.sendgrid.com/ui/sending-email/getting-started-with-automation).  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.lmccampaigns.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class UpdateAScheduledCampaignResponse {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("id")
    @Getter
    @Setter
    private Integer id;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("send_at")
    @Getter
    @Setter
    private Integer sendAt;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("status")
    @Getter
    @Setter
    private String status;

    public UpdateAScheduledCampaignResponse() {}

    private UpdateAScheduledCampaignResponse(Builder builder) {
        this.id = builder.id;
        this.sendAt = builder.sendAt;
        this.status = builder.status;
    }

    // Builder class for constructing object
    public static class Builder {

        private Integer id;
        private Integer sendAt;
        private String status;

        public Builder(Integer id, Integer sendAt, String status) {
            this.id = id;
            this.sendAt = sendAt;
            this.status = status;
        }

        public UpdateAScheduledCampaignResponse build() {
            return new UpdateAScheduledCampaignResponse(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            UpdateAScheduledCampaignResponse.class.getSimpleName() + "(",
            ")"
        );
        if (id != null) joiner.add("id=" + id);
        if (sendAt != null) joiner.add("sendAt=" + sendAt);
        if (status != null) joiner.add("status=" + status);
        return joiner.toString();
    }
}
