/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid IP Address API
 * The Twilio SendGrid IP Address API allows you to add and manage dedicated IP addresses and IP Pools for your SendGrid account and Subusers. If you are sending any significant amount of email, SendGrid typically suggests sending from dedicated IPs. It's also best to send marketing and transactional emails from separate IP addresses. In order to do this, you'll need to set up IP Pools, which are groups of dedicated IP addresses you define to send particular types of messages. See the [**Dedicated IP Addresses**](https://docs.sendgrid.com/ui/account-and-settings/dedicated-ip-addresses) for more information about obtaining and allocating IPs.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.ips.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.StringJoiner;


@ToString
public class PostIps201Response {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("ips")
    @Getter
    @Setter
    private List<PostIps201ResponseIpsInner> ips;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("remainingIps")
    @Getter
    @Setter
    private Integer remainingIps;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("warmup")
    @Getter
    @Setter
    private Boolean warmup;

    public PostIps201Response() {
    }

    private PostIps201Response(Builder builder) {
        this.ips = builder.ips;
        this.remainingIps = builder.remainingIps;
        this.warmup = builder.warmup;
    }

    // Builder class for constructing object
    public static class Builder {
        private List<PostIps201ResponseIpsInner> ips;
        private Integer remainingIps;
        private Boolean warmup;

        public Builder(List<PostIps201ResponseIpsInner> ips, Integer remainingIps, Boolean warmup) {
            this.ips = ips;
            this.remainingIps = remainingIps;
            this.warmup = warmup;
        }

        public PostIps201Response build() {
            return new PostIps201Response(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", PostIps201Response.class.getSimpleName() + "(", ")");
        if (ips != null) joiner.add("ips=" + ips);
        if (remainingIps != null) joiner.add("remainingIps=" + remainingIps);
        if (warmup != null) joiner.add("warmup=" + warmup);
        return joiner.toString();
    }

}
         
    
