/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Domain Authentication API
 * The Twilio SendGrid Domain Authentication API allows you to manage your authenticated domains and their settings.  Domain Authentication is a required step when setting up your Twilio SendGrid account because it's essential to ensuring the deliverability of your email. Domain Authentication signals trustworthiness to email inbox providers and your recipients by approving SendGrid to send email on behalf of your domain. For more information, see [**How to Set Up Domain Authentication**](https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/).  Each user may have a maximum of 3,000 authenticated domains and 3,000 link brandings. This limit is at the user level, meaning each Subuser belonging to a parent account may have its own 3,000 authenticated domains and 3,000 link brandings.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.domainauthentication.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.StringJoiner;


@ToString
public class PostWhitelabelDomainsIdValidate200ResponseValidationResultsSpf {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("valid")
    @Getter
    @Setter
    private Boolean valid;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("reason")
    @Getter
    @Setter
    private String reason;

    public PostWhitelabelDomainsIdValidate200ResponseValidationResultsSpf() {
    }

    private PostWhitelabelDomainsIdValidate200ResponseValidationResultsSpf(Builder builder) {
        this.valid = builder.valid;
        this.reason = builder.reason;
    }

    // Builder class for constructing object
    public static class Builder {
        private Boolean valid;
        private String reason;

        public Builder() {
        }

        public Builder valid(Boolean valid) {
            this.valid = valid;
            return this;
        }

        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        public PostWhitelabelDomainsIdValidate200ResponseValidationResultsSpf build() {
            return new PostWhitelabelDomainsIdValidate200ResponseValidationResultsSpf(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", PostWhitelabelDomainsIdValidate200ResponseValidationResultsSpf.class.getSimpleName() + "(", ")");
        if (valid != null) joiner.add("valid=" + valid);
        if (reason != null) joiner.add("reason=" + reason);
        return joiner.toString();
    }

}
         
    
