/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Marketing Campaigns Contacts API
 * The Twilio SendGrid Marketing Campaigns Contacts API allows you to manage all of your marketing contacts programmatically. You can also import and export contacts using this API. The Contacts API allows you to associate contacts with lists and segments; however, to manage the lists and segments themselves, see the [Lists API](https://docs.sendgrid.com/api-reference/lists/) and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/).  You can also manage your marketing contacts with the [Marketing Campaigns application user interface](https://mc.sendgrid.com/contacts). See [**How to Send Email with New Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/how-to-send-email-with-marketing-campaigns) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.mccontacts.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.mccontacts.models.ExportContactRequestNotifications;
import com.sendgrid.rest.api.v3.mccontacts.models.FileType;
import java.util.List;
import java.util.StringJoiner;
import java.util.UUID;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class ExportContactRequest {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("list_ids")
    @Getter
    @Setter
    private List<UUID> listIds;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("segment_ids")
    @Getter
    @Setter
    private List<String> segmentIds;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("notifications")
    @Getter
    @Setter
    private ExportContactRequestNotifications notifications;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("file_type")
    @Getter
    @Setter
    private FileType fileType;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("max_file_size")
    @Getter
    @Setter
    private Integer maxFileSize;

    public ExportContactRequest() {}

    private ExportContactRequest(Builder builder) {
        this.listIds = builder.listIds;
        this.segmentIds = builder.segmentIds;
        this.notifications = builder.notifications;
        this.fileType = builder.fileType;
        this.maxFileSize = builder.maxFileSize;
    }

    // Builder class for constructing object
    public static class Builder {

        private List<UUID> listIds;
        private List<String> segmentIds;
        private ExportContactRequestNotifications notifications;
        private FileType fileType;
        private Integer maxFileSize;

        public Builder() {}

        public Builder listIds(List<UUID> listIds) {
            this.listIds = listIds;
            return this;
        }

        public Builder segmentIds(List<String> segmentIds) {
            this.segmentIds = segmentIds;
            return this;
        }

        public Builder notifications(
            ExportContactRequestNotifications notifications
        ) {
            this.notifications = notifications;
            return this;
        }

        public Builder fileType(FileType fileType) {
            this.fileType = fileType;
            return this;
        }

        public Builder maxFileSize(Integer maxFileSize) {
            this.maxFileSize = maxFileSize;
            return this;
        }

        public ExportContactRequest build() {
            return new ExportContactRequest(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            ExportContactRequest.class.getSimpleName() + "(",
            ")"
        );
        if (listIds != null) joiner.add("listIds=" + listIds);
        if (segmentIds != null) joiner.add("segmentIds=" + segmentIds);
        if (notifications != null) joiner.add("notifications=" + notifications);
        if (fileType != null) joiner.add("fileType=" + fileType);
        if (maxFileSize != null) joiner.add("maxFileSize=" + maxFileSize);
        return joiner.toString();
    }
}
