/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Marketing Campaigns Contacts API
 * The Twilio SendGrid Marketing Campaigns Contacts API allows you to manage all of your marketing contacts programmatically. You can also import and export contacts using this API. The Contacts API allows you to associate contacts with lists and segments; however, to manage the lists and segments themselves, see the [Lists API](https://docs.sendgrid.com/api-reference/lists/) and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/).  You can also manage your marketing contacts with the [Marketing Campaigns application user interface](https://mc.sendgrid.com/contacts). See [**How to Send Email with New Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/how-to-send-email-with-marketing-campaigns) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.mccontacts.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.mccontacts.models.ListContactCount200ResponseBillableBreakdown;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class ListContactCount200Response {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("contact_count")
    @Getter
    @Setter
    private Integer contactCount;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("billable_count")
    @Getter
    @Setter
    private Integer billableCount;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("billable_breakdown")
    @Getter
    @Setter
    private ListContactCount200ResponseBillableBreakdown billableBreakdown;

    public ListContactCount200Response() {}

    private ListContactCount200Response(Builder builder) {
        this.contactCount = builder.contactCount;
        this.billableCount = builder.billableCount;
        this.billableBreakdown = builder.billableBreakdown;
    }

    // Builder class for constructing object
    public static class Builder {

        private Integer contactCount;
        private Integer billableCount;
        private ListContactCount200ResponseBillableBreakdown billableBreakdown;

        public Builder(Integer contactCount) {
            this.contactCount = contactCount;
        }

        public Builder billableCount(Integer billableCount) {
            this.billableCount = billableCount;
            return this;
        }

        public Builder billableBreakdown(
            ListContactCount200ResponseBillableBreakdown billableBreakdown
        ) {
            this.billableBreakdown = billableBreakdown;
            return this;
        }

        public ListContactCount200Response build() {
            return new ListContactCount200Response(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            ListContactCount200Response.class.getSimpleName() + "(",
            ")"
        );
        if (contactCount != null) joiner.add("contactCount=" + contactCount);
        if (billableCount != null) joiner.add("billableCount=" + billableCount);
        if (billableBreakdown != null) joiner.add(
            "billableBreakdown=" + billableBreakdown
        );
        return joiner.toString();
    }
}
