/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Integrations API
 * Integrations allows you to connect your SendGrid applications with third-party services and forward SendGrid email events to those external applications. Currently, Integrations supports event forwarding to [Segment](https://segment.com/docs). You can use this API to create, delete, view, and update your Integrations.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.integrations.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sendgrid.converter.Promoter;

public enum Items {
    DROP("drop"),

    PROCESSED("processed"),

    DEFERRED("deferred"),

    GROUP_UNSUBSCRIBE("group_unsubscribe"),

    BOUNCE("bounce"),

    DELIVERED("delivered"),

    CLICK("click"),

    UNSUBSCRIBE("unsubscribe"),

    OPEN("open"),

    GROUP_RESUBSCRIBE("group_resubscribe"),

    SPAMREPORT("spamreport"),

    MACHINE_OPENED("machine_opened");

    private final String value;

    private Items(final String value) {
        this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
        return value;
    }

    @JsonCreator
    public static Items forValue(final String value) {
        return Promoter.enumFromString(value, Items.values());
    }
}
