/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Teammates API
 * The Twilio SendGrid Teammates API allows you to add, manage, and remove Teammates, or user accounts, from your SendGrid account. Teammates function like user accounts on the SendGrid account, allowing you to invite additional users to your account with scoped access. You can think of Teammates as SendGrid's approach to enabling [role-based access control](https://en.wikipedia.org/wiki/Role-based_access_control) for your SendGrid account. For even more control over the access to your account, see the [Twilio SendGrid SSO API](https://docs.sendgrid.com/api-reference/single-sign-on-teammates/), which enables SSO-authenticated Teammates to be managed through a SAML 2.0 identity provider.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.teammates.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.teammates.models.ListSubuserByTemplate200ResponseMetadata;
import com.sendgrid.rest.api.v3.teammates.models.ListSubuserByTemplate200ResponseSubuserAccessInner;
import java.util.List;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class ListSubuserByTemplate200Response {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("has_restricted_subuser_access")
    @Getter
    @Setter
    private Boolean hasRestrictedSubuserAccess;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("subuser_access")
    @Getter
    @Setter
    private List<
        ListSubuserByTemplate200ResponseSubuserAccessInner
    > subuserAccess;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("_metadata")
    @Getter
    @Setter
    private ListSubuserByTemplate200ResponseMetadata metadata;

    public ListSubuserByTemplate200Response() {}

    private ListSubuserByTemplate200Response(Builder builder) {
        this.hasRestrictedSubuserAccess = builder.hasRestrictedSubuserAccess;
        this.subuserAccess = builder.subuserAccess;
        this.metadata = builder.metadata;
    }

    // Builder class for constructing object
    public static class Builder {

        private Boolean hasRestrictedSubuserAccess;
        private List<
            ListSubuserByTemplate200ResponseSubuserAccessInner
        > subuserAccess;
        private ListSubuserByTemplate200ResponseMetadata metadata;

        public Builder() {}

        public Builder hasRestrictedSubuserAccess(
            Boolean hasRestrictedSubuserAccess
        ) {
            this.hasRestrictedSubuserAccess = hasRestrictedSubuserAccess;
            return this;
        }

        public Builder subuserAccess(
            List<
                ListSubuserByTemplate200ResponseSubuserAccessInner
            > subuserAccess
        ) {
            this.subuserAccess = subuserAccess;
            return this;
        }

        public Builder metadata(
            ListSubuserByTemplate200ResponseMetadata metadata
        ) {
            this.metadata = metadata;
            return this;
        }

        public ListSubuserByTemplate200Response build() {
            return new ListSubuserByTemplate200Response(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            ListSubuserByTemplate200Response.class.getSimpleName() + "(",
            ")"
        );
        if (hasRestrictedSubuserAccess != null) joiner.add(
            "hasRestrictedSubuserAccess=" + hasRestrictedSubuserAccess
        );
        if (subuserAccess != null) joiner.add("subuserAccess=" + subuserAccess);
        if (metadata != null) joiner.add("metadata=" + metadata);
        return joiner.toString();
    }
}
