/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Subusers
 * The Twilio SendGrid Subusers API allows you to create and manage your Subuser accounts. Subusers are available on [Pro and Premier plans](https://sendgrid.com/pricing), and you can think of them as sub-accounts. Each Subuser can have its own sending domains, IP addresses, and reporting. SendGrid recommends creating Subusers for each of the different types of emails you send—one Subuser for transactional emails and another for marketing emails. Independent Software Vendor (ISV) customers may also create Subusers for each of their customers.  You can also manage Subusers in the [Twilio SendGrid application user interface](https://app.sendgrid.com/settings/subusers). See [**Subusers**](https://docs.sendgrid.com/ui/account-and-settings/subusers) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.subusers.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.subusers.models.CategoryStatsStatsInnerMetrics;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class CategoryStatsStatsInner {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("metrics")
    @Getter
    @Setter
    private CategoryStatsStatsInnerMetrics metrics;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("name")
    @Getter
    @Setter
    private String name;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("type")
    @Getter
    @Setter
    private String type;

    public CategoryStatsStatsInner() {}

    private CategoryStatsStatsInner(Builder builder) {
        this.metrics = builder.metrics;
        this.name = builder.name;
        this.type = builder.type;
    }

    // Builder class for constructing object
    public static class Builder {

        private CategoryStatsStatsInnerMetrics metrics;
        private String name;
        private String type;

        public Builder(String type) {
            this.type = type;
        }

        public Builder metrics(CategoryStatsStatsInnerMetrics metrics) {
            this.metrics = metrics;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public CategoryStatsStatsInner build() {
            return new CategoryStatsStatsInner(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            CategoryStatsStatsInner.class.getSimpleName() + "(",
            ")"
        );
        if (metrics != null) joiner.add("metrics=" + metrics);
        if (name != null) joiner.add("name=" + name);
        if (type != null) joiner.add("type=" + type);
        return joiner.toString();
    }
}
