/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Marketing Campaigns Custom Fields API
 * The Twilio SendGrid Marketing Campaigns Custom Fields API allows you to add extra information about your marketing contacts that is relevant to your needs. For example, a fashion retailer might create a custom field for customers' shoe sizes, an ice cream shop might store customers' favorite flavors in a custom field, and you can create custom fields that make sense for your business.  With custom fields, you can also create [segments](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) based on custom fields values. Your custom fields are completely customizable to the use-cases and user information that you need.  You can also manage your Custom Fields using the SendGrid application user interface. See [**Using Custom Fields**](https://docs.sendgrid.com/ui/managing-contacts/custom-fields) for more information, including a list of Reserved Fields. You can also manage your custom fields in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/custom-fields).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.mccustomfields.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.mccustomfields.models.CustomFieldDefinitionsResponse;
import com.sendgrid.rest.api.v3.mccustomfields.models.Metadata;
import com.sendgrid.rest.api.v3.mccustomfields.models.ReservedFieldDefinitionsResponseInner;
import java.util.List;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class ListFieldDefinition200Response {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("custom_fields")
    @Getter
    @Setter
    private List<CustomFieldDefinitionsResponse> customFields;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("reserved_fields")
    @Getter
    @Setter
    private List<ReservedFieldDefinitionsResponseInner> reservedFields;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("_metadata")
    @Getter
    @Setter
    private Metadata metadata;

    public ListFieldDefinition200Response() {}

    private ListFieldDefinition200Response(Builder builder) {
        this.customFields = builder.customFields;
        this.reservedFields = builder.reservedFields;
        this.metadata = builder.metadata;
    }

    // Builder class for constructing object
    public static class Builder {

        private List<CustomFieldDefinitionsResponse> customFields;
        private List<ReservedFieldDefinitionsResponseInner> reservedFields;
        private Metadata metadata;

        public Builder(
            List<CustomFieldDefinitionsResponse> customFields,
            List<ReservedFieldDefinitionsResponseInner> reservedFields
        ) {
            this.customFields = customFields;
            this.reservedFields = reservedFields;
        }

        public Builder metadata(Metadata metadata) {
            this.metadata = metadata;
            return this;
        }

        public ListFieldDefinition200Response build() {
            return new ListFieldDefinition200Response(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            ListFieldDefinition200Response.class.getSimpleName() + "(",
            ")"
        );
        if (customFields != null) joiner.add("customFields=" + customFields);
        if (reservedFields != null) joiner.add(
            "reservedFields=" + reservedFields
        );
        if (metadata != null) joiner.add("metadata=" + metadata);
        return joiner.toString();
    }
}
