/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Email Address Validation API
 * The Twilio SendGrid Email Address Validation API provides real-time detailed information on the validity of email addresses. You can integrate this validation process into your platform's signup form and customize the best use of email address validation for your use case.  Email Address Validation is available to [Email API Pro and Premier level accounts](https://sendgrid.com/pricing) only. Prior to upgrading your account to Pro or Premier, you will not see the option to create an Email Validation API key. An Email Validation API key is separate from and in addition to your other keys, including Full Access API keys.  You can use this API to: - Indicate to users that the address they have entered into a form is invalid. - Drop invalid email addresses from your database. - Suppress invalid email addresses from your sending to decrease your bounce rate.  See [**Email Address Validation**](https://docs.sendgrid.com/ui/managing-contacts/email-address-validation) for more information.  You can also view your Email Validation results and metrics in the Validation section of the [Twilio SendGrid application user interface](https://docs.sendgrid.com/ui/managing-contacts/email-address-validation).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.emailvalidation.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class PutValidationsEmailJobs200ResponseUploadHeadersInner {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("header")
    @Getter
    @Setter
    private String header;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("value")
    @Getter
    @Setter
    private String value;

    public PutValidationsEmailJobs200ResponseUploadHeadersInner() {}

    private PutValidationsEmailJobs200ResponseUploadHeadersInner(
        Builder builder
    ) {
        this.header = builder.header;
        this.value = builder.value;
    }

    // Builder class for constructing object
    public static class Builder {

        private String header;
        private String value;

        public Builder() {}

        public Builder header(String header) {
            this.header = header;
            return this;
        }

        public Builder value(String value) {
            this.value = value;
            return this;
        }

        public PutValidationsEmailJobs200ResponseUploadHeadersInner build() {
            return new PutValidationsEmailJobs200ResponseUploadHeadersInner(
                this
            );
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            PutValidationsEmailJobs200ResponseUploadHeadersInner.class.getSimpleName() +
            "(",
            ")"
        );
        if (header != null) joiner.add("header=" + header);
        if (value != null) joiner.add("value=" + value);
        return joiner.toString();
    }
}
