/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Marketing Campaigns Send Test Email API
 * The Twilio SendGrid Test Email API allows you to test a marketing email by first sending it to a list of up to 10 email addresses before pushing to a contact list or segment. With this feature, you can test the layout and content of your message in multiple email clients and with multiple recipients to see how it will function in a real-world scenario.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.mctest.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.StringJoiner;


@ToString
public class ErrorResponse {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("errors")
    @Getter
    @Setter
    private List<ErrorResponseErrorsInner> errors;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("id")
    @Getter
    @Setter
    private String id;

    public ErrorResponse() {
    }

    private ErrorResponse(Builder builder) {
        this.errors = builder.errors;
        this.id = builder.id;
    }

    // Builder class for constructing object
    public static class Builder {
        private List<ErrorResponseErrorsInner> errors;
        private String id;

        public Builder() {
        }

        public Builder errors(List<ErrorResponseErrorsInner> errors) {
            this.errors = errors;
            return this;
        }

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public ErrorResponse build() {
            return new ErrorResponse(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", ErrorResponse.class.getSimpleName() + "(", ")");
        if (errors != null) joiner.add("errors=" + errors);
        if (id != null) joiner.add("id=" + id);
        return joiner.toString();
    }

}
         
    
