/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid IP Access Management API
 * IP Twilio SendGrid IP Access Management API allows you to control which IP addresses can be used to access your account, either through the SendGrid application user interface or the API.  There is no limit to the number of IP addresses that you can allow.  It is possible to remove your own IP address from your list of allowed addresses, thus blocking your own access to your account. While we are able to restore your access, we do require thorough proof of your identify and ownership of your account. We take the security of your account very seriously and wish to prevent any 'bad actors' from maliciously gaining access to your account. Your current IP is clearly displayed to help prevent you from accidentally removing it from the allowed addresses.  See [**IP Access Management**](https://docs.sendgrid.com/ui/account-and-settings/ip-access-management) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.ipaccessmanagement.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.StringJoiner;


@ToString
public class IpAccessManagement2xxResultInner {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("id")
    @Getter
    @Setter
    private Integer id;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("ip")
    @Getter
    @Setter
    private String ip;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("createdAt")
    @Getter
    @Setter
    private Integer createdAt;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("updatedAt")
    @Getter
    @Setter
    private Integer updatedAt;

    public IpAccessManagement2xxResultInner() {
    }

    private IpAccessManagement2xxResultInner(Builder builder) {
        this.id = builder.id;
        this.ip = builder.ip;
        this.createdAt = builder.createdAt;
        this.updatedAt = builder.updatedAt;
    }

    // Builder class for constructing object
    public static class Builder {
        private Integer id;
        private String ip;
        private Integer createdAt;
        private Integer updatedAt;

        public Builder() {
        }

        public Builder id(Integer id) {
            this.id = id;
            return this;
        }

        public Builder ip(String ip) {
            this.ip = ip;
            return this;
        }

        public Builder createdAt(Integer createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder updatedAt(Integer updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public IpAccessManagement2xxResultInner build() {
            return new IpAccessManagement2xxResultInner(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", IpAccessManagement2xxResultInner.class.getSimpleName() + "(", ")");
        if (id != null) joiner.add("id=" + id);
        if (ip != null) joiner.add("ip=" + ip);
        if (createdAt != null) joiner.add("createdAt=" + createdAt);
        if (updatedAt != null) joiner.add("updatedAt=" + updatedAt);
        return joiner.toString();
    }

}
         
    
