/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Scopes API
 * The Twilio SendGrid Scopes API allows you to retrieve the scopes or permissions available to a user, see the user's attempts to access your SendGrid account, and, if necessary, deny an access request.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.scopes.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.StringJoiner;


@ToString
public class GetScopes200Response {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("scopes")
    @Getter
    @Setter
    private List<String> scopes;

    public GetScopes200Response() {
    }

    private GetScopes200Response(Builder builder) {
        this.scopes = builder.scopes;
    }

    // Builder class for constructing object
    public static class Builder {
        private List<String> scopes;

        public Builder(List<String> scopes) {
            this.scopes = scopes;
        }

        public GetScopes200Response build() {
            return new GetScopes200Response(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", GetScopes200Response.class.getSimpleName() + "(", ")");
        if (scopes != null) joiner.add("scopes=" + scopes);
        return joiner.toString();
    }

}
         
    
