/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid IP Address Management API
 * The Twilio SendGrid IP Address Management API combines functionality that was previously split between the Twilio SendGrid [IP Address API](https://docs.sendgrid.com/api-reference/ip-address) and [IP Pools API](https://docs.sendgrid.com/api-reference/ip-pools). This functionality includes adding IP addresses to your account, assigning IP addresses to IP Pools and Subusers, among other tasks.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.ipaddressmanagement.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.StringJoiner;


@ToString
public class GetSendIpsIps200ResponseResultInner {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("ip")
    @Getter
    @Setter
    private String ip;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("pools")
    @Getter
    @Setter
    private List<GetSendIpsIps200ResponseResultInnerPoolsInner> pools;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("isAutoWarmup")
    @Getter
    @Setter
    private Boolean isAutoWarmup;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("isParentAssigned")
    @Getter
    @Setter
    private Boolean isParentAssigned;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("updatedAt")
    @Getter
    @Setter
    private Integer updatedAt;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("isEnabled")
    @Getter
    @Setter
    private Boolean isEnabled;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("isLeased")
    @Getter
    @Setter
    private Boolean isLeased;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("addedAt")
    @Getter
    @Setter
    private Integer addedAt;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("region")
    @Getter
    @Setter
    private Region region;

    public GetSendIpsIps200ResponseResultInner() {
    }

    private GetSendIpsIps200ResponseResultInner(Builder builder) {
        this.ip = builder.ip;
        this.pools = builder.pools;
        this.isAutoWarmup = builder.isAutoWarmup;
        this.isParentAssigned = builder.isParentAssigned;
        this.updatedAt = builder.updatedAt;
        this.isEnabled = builder.isEnabled;
        this.isLeased = builder.isLeased;
        this.addedAt = builder.addedAt;
        this.region = builder.region;
    }

    // Builder class for constructing object
    public static class Builder {
        private String ip;
        private List<GetSendIpsIps200ResponseResultInnerPoolsInner> pools;
        private Boolean isAutoWarmup;
        private Boolean isParentAssigned;
        private Integer updatedAt;
        private Boolean isEnabled;
        private Boolean isLeased;
        private Integer addedAt;
        private Region region;

        public Builder() {
        }

        public Builder ip(String ip) {
            this.ip = ip;
            return this;
        }

        public Builder pools(List<GetSendIpsIps200ResponseResultInnerPoolsInner> pools) {
            this.pools = pools;
            return this;
        }

        public Builder isAutoWarmup(Boolean isAutoWarmup) {
            this.isAutoWarmup = isAutoWarmup;
            return this;
        }

        public Builder isParentAssigned(Boolean isParentAssigned) {
            this.isParentAssigned = isParentAssigned;
            return this;
        }

        public Builder updatedAt(Integer updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder isEnabled(Boolean isEnabled) {
            this.isEnabled = isEnabled;
            return this;
        }

        public Builder isLeased(Boolean isLeased) {
            this.isLeased = isLeased;
            return this;
        }

        public Builder addedAt(Integer addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        public Builder region(Region region) {
            this.region = region;
            return this;
        }

        public GetSendIpsIps200ResponseResultInner build() {
            return new GetSendIpsIps200ResponseResultInner(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", GetSendIpsIps200ResponseResultInner.class.getSimpleName() + "(", ")");
        if (ip != null) joiner.add("ip=" + ip);
        if (pools != null) joiner.add("pools=" + pools);
        if (isAutoWarmup != null) joiner.add("isAutoWarmup=" + isAutoWarmup);
        if (isParentAssigned != null) joiner.add("isParentAssigned=" + isParentAssigned);
        if (updatedAt != null) joiner.add("updatedAt=" + updatedAt);
        if (isEnabled != null) joiner.add("isEnabled=" + isEnabled);
        if (isLeased != null) joiner.add("isLeased=" + isLeased);
        if (addedAt != null) joiner.add("addedAt=" + addedAt);
        if (region != null) joiner.add("region=" + region);
        return joiner.toString();
    }

}
         
    
