/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid IP Address Management API
 * The Twilio SendGrid IP Address Management API combines functionality that was previously split between the Twilio SendGrid [IP Address API](https://docs.sendgrid.com/api-reference/ip-address) and [IP Pools API](https://docs.sendgrid.com/api-reference/ip-pools). This functionality includes adding IP addresses to your account, assigning IP addresses to IP Pools and Subusers, among other tasks.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.ipaddressmanagement.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.StringJoiner;


@ToString
public class GetSendIpsIps200ResponseResultInnerPoolsInner {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("name")
    @Getter
    @Setter
    private String name;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("id")
    @Getter
    @Setter
    private String id;

    public GetSendIpsIps200ResponseResultInnerPoolsInner() {
    }

    private GetSendIpsIps200ResponseResultInnerPoolsInner(Builder builder) {
        this.name = builder.name;
        this.id = builder.id;
    }

    // Builder class for constructing object
    public static class Builder {
        private String name;
        private String id;

        public Builder() {
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public Builder id(String id) {
            this.id = id;
            return this;
        }

        public GetSendIpsIps200ResponseResultInnerPoolsInner build() {
            return new GetSendIpsIps200ResponseResultInnerPoolsInner(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", GetSendIpsIps200ResponseResultInnerPoolsInner.class.getSimpleName() + "(", ")");
        if (name != null) joiner.add("name=" + name);
        if (id != null) joiner.add("id=" + id);
        return joiner.toString();
    }

}
         
    
