/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Account Provisioning API
 * The Twilio SendGrid Account Provisioning API provides a platform for Twilio SendGrid resellers to manage their customer accounts. This API is for companies that have a formal reseller partnership with Twilio SendGrid.  You can access Twilio SendGrid sub-account functionality without becoming a reseller. If you require sub-account functionality, see the Twilio [SendGrid Subusers](https://docs.sendgrid.com/ui/account-and-settings/subusers) feature, which is available with [Pro and Premier plans](https://sendgrid.com/pricing/).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.accountprovisioning.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.accountprovisioning.models.AccountProvisioningOfferingV1;
import com.sendgrid.rest.api.v3.accountprovisioning.models.CatalogEntryEntitlements;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class CatalogEntry {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("offering")
    @Getter
    @Setter
    private AccountProvisioningOfferingV1 offering;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("entitlements")
    @Getter
    @Setter
    private CatalogEntryEntitlements entitlements;

    public CatalogEntry() {}

    private CatalogEntry(Builder builder) {
        this.offering = builder.offering;
        this.entitlements = builder.entitlements;
    }

    // Builder class for constructing object
    public static class Builder {

        private AccountProvisioningOfferingV1 offering;
        private CatalogEntryEntitlements entitlements;

        public Builder() {}

        public Builder offering(AccountProvisioningOfferingV1 offering) {
            this.offering = offering;
            return this;
        }

        public Builder entitlements(CatalogEntryEntitlements entitlements) {
            this.entitlements = entitlements;
            return this;
        }

        public CatalogEntry build() {
            return new CatalogEntry(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            CatalogEntry.class.getSimpleName() + "(",
            ")"
        );
        if (offering != null) joiner.add("offering=" + offering);
        if (entitlements != null) joiner.add("entitlements=" + entitlements);
        return joiner.toString();
    }
}
