/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Webhook Configuration API
 * The Twilio SendGrid Webhooks API allows you to configure the Event and Parse Webhooks.  Email is a data-rich channel, and implementing the Event Webhook will allow you to consume those data in nearly real time. This means you can actively monitor and participate in the health of your email program throughout the send cycle.  The Inbound Parse Webhook processes all incoming email for a domain or subdomain, parses the contents and attachments and then POSTs `multipart/form-data` to a URL that you choose.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.webhooks.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.webhooks.models.EventWebhookSignedResponse;
import java.math.BigDecimal;
import java.util.List;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class EventWebhookAllResponse {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("max_allowed")
    @Getter
    @Setter
    private BigDecimal maxAllowed;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("webhooks")
    @Getter
    @Setter
    private List<EventWebhookSignedResponse> webhooks;

    public EventWebhookAllResponse() {}

    private EventWebhookAllResponse(Builder builder) {
        this.maxAllowed = builder.maxAllowed;
        this.webhooks = builder.webhooks;
    }

    // Builder class for constructing object
    public static class Builder {

        private BigDecimal maxAllowed;
        private List<EventWebhookSignedResponse> webhooks;

        public Builder() {}

        public Builder maxAllowed(BigDecimal maxAllowed) {
            this.maxAllowed = maxAllowed;
            return this;
        }

        public Builder webhooks(List<EventWebhookSignedResponse> webhooks) {
            this.webhooks = webhooks;
            return this;
        }

        public EventWebhookAllResponse build() {
            return new EventWebhookAllResponse(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            EventWebhookAllResponse.class.getSimpleName() + "(",
            ")"
        );
        if (maxAllowed != null) joiner.add("maxAllowed=" + maxAllowed);
        if (webhooks != null) joiner.add("webhooks=" + webhooks);
        return joiner.toString();
    }
}
