/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Webhook Configuration API
 * The Twilio SendGrid Webhooks API allows you to configure the Event and Parse Webhooks.  Email is a data-rich channel, and implementing the Event Webhook will allow you to consume those data in nearly real time. This means you can actively monitor and participate in the health of your email program throughout the send cycle.  The Inbound Parse Webhook processes all incoming email for a domain or subdomain, parses the contents and attachments and then POSTs `multipart/form-data` to a URL that you choose.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.webhooks.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.List;
import java.util.StringJoiner;


@ToString
public class PostUserWebhooksEventSettings400ResponseAnyOf1 {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("errors")
    @Getter
    @Setter
    private List<PostUserWebhooksEventSettings400ResponseAnyOf1ErrorsInner> errors;

    public PostUserWebhooksEventSettings400ResponseAnyOf1() {
    }

    private PostUserWebhooksEventSettings400ResponseAnyOf1(Builder builder) {
        this.errors = builder.errors;
    }

    // Builder class for constructing object
    public static class Builder {
        private List<PostUserWebhooksEventSettings400ResponseAnyOf1ErrorsInner> errors;

        public Builder() {
        }

        public Builder errors(List<PostUserWebhooksEventSettings400ResponseAnyOf1ErrorsInner> errors) {
            this.errors = errors;
            return this;
        }

        public PostUserWebhooksEventSettings400ResponseAnyOf1 build() {
            return new PostUserWebhooksEventSettings400ResponseAnyOf1(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", PostUserWebhooksEventSettings400ResponseAnyOf1.class.getSimpleName() + "(", ")");
        if (errors != null) joiner.add("errors=" + errors);
        return joiner.toString();
    }

}
         
    
