/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Email Activity API
 * The Twilio SendGrid Email Activity API allows you to query all of your stored messages, query individual messages, and download a CSV with data about the stored messages. Once retrieved, you can inspect the data associated with your messages to better understand your mail send. For example, you may retrieve all bounced messages or all messages with the same subject line and search for commonalities among them.  You must [purchase additional email activity history](https://app.sendgrid.com/settings/billing/addons/email_activity) to gain access to the Email Activity Feed API.  See **Getting Started with the Email Activity Feed API** for help building queries and working with this API. You can also work with email activity in the **Activity** section of the [Twilio SendGrid application user interface](https://app.sendgrid.com/email_activity).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.emailactivity.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.StringJoiner;


@ToString
public class AbbvMessage {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("fromEmail")
    @Getter
    @Setter
    private String fromEmail;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("msgId")
    @Getter
    @Setter
    private String msgId;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("subject")
    @Getter
    @Setter
    private String subject;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("toEmail")
    @Getter
    @Setter
    private String toEmail;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("status")
    @Getter
    @Setter
    private Status status;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("opensCount")
    @Getter
    @Setter
    private Object opensCount;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("clicksCount")
    @Getter
    @Setter
    private Object clicksCount;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("lastEventTime")
    @Getter
    @Setter
    private Object lastEventTime;

    public AbbvMessage() {
    }

    private AbbvMessage(Builder builder) {
        this.fromEmail = builder.fromEmail;
        this.msgId = builder.msgId;
        this.subject = builder.subject;
        this.toEmail = builder.toEmail;
        this.status = builder.status;
        this.opensCount = builder.opensCount;
        this.clicksCount = builder.clicksCount;
        this.lastEventTime = builder.lastEventTime;
    }

    // Builder class for constructing object
    public static class Builder {
        private String fromEmail;
        private String msgId;
        private String subject;
        private String toEmail;
        private Status status;
        private Object opensCount;
        private Object clicksCount;
        private Object lastEventTime;

        public Builder(String fromEmail, String msgId, String subject, String toEmail, Status status, Object opensCount, Object clicksCount, Object lastEventTime) {
            this.fromEmail = fromEmail;
            this.msgId = msgId;
            this.subject = subject;
            this.toEmail = toEmail;
            this.status = status;
            this.opensCount = opensCount;
            this.clicksCount = clicksCount;
            this.lastEventTime = lastEventTime;
        }

        public AbbvMessage build() {
            return new AbbvMessage(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", AbbvMessage.class.getSimpleName() + "(", ")");
        if (fromEmail != null) joiner.add("fromEmail=" + fromEmail);
        if (msgId != null) joiner.add("msgId=" + msgId);
        if (subject != null) joiner.add("subject=" + subject);
        if (toEmail != null) joiner.add("toEmail=" + toEmail);
        if (status != null) joiner.add("status=" + status);
        if (opensCount != null) joiner.add("opensCount=" + opensCount);
        if (clicksCount != null) joiner.add("clicksCount=" + clicksCount);
        if (lastEventTime != null) joiner.add("lastEventTime=" + lastEventTime);
        return joiner.toString();
    }

}
         
    
