/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Marketing Campaigns Statistics API
 * The Marketing Campaigns Stats API allows you to retrieve statistics for both Automations and Single Sends. The statistics provided include bounces, clicks, opens, and more. You can export stats in CSV format for use in other applications. You can also retrieve Marketing Campaigns stats in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/).  This API provides statistics for Marketing Campaigns only. For stats related to event tracking, please see the [Stats API](https://docs.sendgrid.com/api-reference/stats).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.mcstats.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.sendgrid.rest.api.v3.mcstats.models.AbPhase;
import com.sendgrid.rest.api.v3.mcstats.models.Metrics;
import java.util.StringJoiner;
import java.util.UUID;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class SinglesendsResponseResultsInner {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("id")
    @Getter
    @Setter
    private UUID id;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("ab_variation")
    @Getter
    @Setter
    private UUID abVariation;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("ab_phase")
    @Getter
    @Setter
    private AbPhase abPhase;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("aggregation")
    @Getter
    @Setter
    private String aggregation;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("stats")
    @Getter
    @Setter
    private Metrics stats;

    public SinglesendsResponseResultsInner() {}

    private SinglesendsResponseResultsInner(Builder builder) {
        this.id = builder.id;
        this.abVariation = builder.abVariation;
        this.abPhase = builder.abPhase;
        this.aggregation = builder.aggregation;
        this.stats = builder.stats;
    }

    // Builder class for constructing object
    public static class Builder {

        private UUID id;
        private UUID abVariation;
        private AbPhase abPhase;
        private String aggregation;
        private Metrics stats;

        public Builder(UUID id, UUID abVariation, AbPhase abPhase) {
            this.id = id;
            this.abVariation = abVariation;
            this.abPhase = abPhase;
        }

        public Builder aggregation(String aggregation) {
            this.aggregation = aggregation;
            return this;
        }

        public Builder stats(Metrics stats) {
            this.stats = stats;
            return this;
        }

        public SinglesendsResponseResultsInner build() {
            return new SinglesendsResponseResultsInner(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            SinglesendsResponseResultsInner.class.getSimpleName() + "(",
            ")"
        );
        if (id != null) joiner.add("id=" + id);
        if (abVariation != null) joiner.add("abVariation=" + abVariation);
        if (abPhase != null) joiner.add("abPhase=" + abPhase);
        if (aggregation != null) joiner.add("aggregation=" + aggregation);
        if (stats != null) joiner.add("stats=" + stats);
        return joiner.toString();
    }
}
