/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Suppressions API
 * The Twilio SendGrid Suppressions API allows you to manage your Suppressions or Unsubscribes and Suppression or Unsubscribe groups. With SendGrid, an unsubscribe is the action an email recipient takes when they opt-out of receiving your messages. A suppression is the action you take as a sender to filter or suppress an unsubscribed address from your email send. From the perspective of the recipient, your suppression is the result of their unsubscribe.  You can have global suppressions, which represent addresses that have been unsubscribed from all of your emails. You can also have suppression groups, also known as ASM groups, which represent categories or groups of emails that your recipients can unsubscribe from, rather than unsubscribing from all of your messages.  SendGrid automatically suppresses emails sent to users for a variety of reasons, including blocks, bounces, invalid email addresses, spam reports, and unsubscribes. SendGrid suppresses these messages to help you maintain the best possible sender reputation by attempting to prevent unwanted mail. You may also add addresses to your suppressions.  See [**Suppressions**](https://docs.sendgrid.com/for-developers/sending-email/suppressions) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.suppressions.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.math.BigDecimal;
import java.util.StringJoiner;


@ToString
public class BounceResponse {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("created")
    @Getter
    @Setter
    private BigDecimal created;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("email")
    @Getter
    @Setter
    private String email;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("reason")
    @Getter
    @Setter
    private String reason;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("status")
    @Getter
    @Setter
    private String status;

    public BounceResponse() {
    }

    private BounceResponse(Builder builder) {
        this.created = builder.created;
        this.email = builder.email;
        this.reason = builder.reason;
        this.status = builder.status;
    }

    // Builder class for constructing object
    public static class Builder {
        private BigDecimal created;
        private String email;
        private String reason;
        private String status;

        public Builder() {
        }

        public Builder created(BigDecimal created) {
            this.created = created;
            return this;
        }

        public Builder email(String email) {
            this.email = email;
            return this;
        }

        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        public Builder status(String status) {
            this.status = status;
            return this;
        }

        public BounceResponse build() {
            return new BounceResponse(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", BounceResponse.class.getSimpleName() + "(", ")");
        if (created != null) joiner.add("created=" + created);
        if (email != null) joiner.add("email=" + email);
        if (reason != null) joiner.add("reason=" + reason);
        if (status != null) joiner.add("status=" + status);
        return joiner.toString();
    }

}
         
    
