/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Mail API
 * The Twilio SendGrid v3 Mail API allows you to send email at scale over HTTP. The Mail Send endpoint supports many levels of functionality, allowing you to send templates, set categories and custom arguments that can be used to analyze your send, and configure which tracking settings to include such as opens and clicks. You can also group mail sends into batches, allowing you to schedule and cancel sends by their batch IDs.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.mail.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class SendMailRequestTrackingSettingsGanalytics {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("enable")
    @Getter
    @Setter
    private Boolean enable;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("utm_source")
    @Getter
    @Setter
    private String utmSource;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("utm_medium")
    @Getter
    @Setter
    private String utmMedium;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("utm_term")
    @Getter
    @Setter
    private String utmTerm;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("utm_content")
    @Getter
    @Setter
    private String utmContent;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("utm_campaign")
    @Getter
    @Setter
    private String utmCampaign;

    public SendMailRequestTrackingSettingsGanalytics() {}

    private SendMailRequestTrackingSettingsGanalytics(Builder builder) {
        this.enable = builder.enable;
        this.utmSource = builder.utmSource;
        this.utmMedium = builder.utmMedium;
        this.utmTerm = builder.utmTerm;
        this.utmContent = builder.utmContent;
        this.utmCampaign = builder.utmCampaign;
    }

    // Builder class for constructing object
    public static class Builder {

        private Boolean enable;
        private String utmSource;
        private String utmMedium;
        private String utmTerm;
        private String utmContent;
        private String utmCampaign;

        public Builder() {}

        public Builder enable(Boolean enable) {
            this.enable = enable;
            return this;
        }

        public Builder utmSource(String utmSource) {
            this.utmSource = utmSource;
            return this;
        }

        public Builder utmMedium(String utmMedium) {
            this.utmMedium = utmMedium;
            return this;
        }

        public Builder utmTerm(String utmTerm) {
            this.utmTerm = utmTerm;
            return this;
        }

        public Builder utmContent(String utmContent) {
            this.utmContent = utmContent;
            return this;
        }

        public Builder utmCampaign(String utmCampaign) {
            this.utmCampaign = utmCampaign;
            return this;
        }

        public SendMailRequestTrackingSettingsGanalytics build() {
            return new SendMailRequestTrackingSettingsGanalytics(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            SendMailRequestTrackingSettingsGanalytics.class.getSimpleName() +
            "(",
            ")"
        );
        if (enable != null) joiner.add("enable=" + enable);
        if (utmSource != null) joiner.add("utmSource=" + utmSource);
        if (utmMedium != null) joiner.add("utmMedium=" + utmMedium);
        if (utmTerm != null) joiner.add("utmTerm=" + utmTerm);
        if (utmContent != null) joiner.add("utmContent=" + utmContent);
        if (utmCampaign != null) joiner.add("utmCampaign=" + utmCampaign);
        return joiner.toString();
    }
}
