/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Legacy Marketing Campaigns Contacts API
 * The Twilio SendGrid Legacy Marketing Campaigns Contacts API allows you to manage your marketing contacts programmatically. This API is operational, but we recommend using the current version of Marketing Campaigns' [Contacts API](https://docs.sendgrid.com/api-reference/contacts/), [Lists API](https://docs.sendgrid.com/api-reference/lists/), and [Segments API](https://docs.sendgrid.com/api-reference/segmenting-contacts-v2/) to manage your contacts.  See [**Migrating from Legacy Marketing Campaigns**](https://docs.sendgrid.com/ui/sending-email/migrating-from-legacy-marketing-campaigns) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.lmccontactdb.models;

import java.util.StringJoiner;
import lombok.ToString;

@ToString
public class SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue {

    public SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue() {}

    private SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue(
        Builder builder
    ) {}

    // Builder class for constructing object
    public static class Builder {

        public Builder() {}

        public SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue build() {
            return new SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue(
                this
            );
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            SearchRecipient200ResponseRecipientsInnerCustomFieldsInnerValue.class.getSimpleName() +
            "(",
            ")"
        );
        return joiner.toString();
    }
}
