/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Statistics API
 * The Twilio SendGrid Statistics API allows you to retrieve the various statistics related to your email program.  Tracking your emails is an important part of being a good sender and learning about how your users interact with your email. This includes everything from clicks and opens to looking at which browsers and mailbox providers your customers use.  SendGrid has broken up statistics in specific ways so that you can get at-a-glance data, as well as the details of how your email is being used.  Category statistics are available for the previous thirteen months only.  See [**Statistics Overview**](https://docs.sendgrid.com/ui/analytics-and-reporting/stats-overview) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.stats.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.StringJoiner;


@ToString
public class AdvancedStatsClicksOpens {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("clicks")
    @Getter
    @Setter
    private Object clicks;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("uniqueClicks")
    @Getter
    @Setter
    private Object uniqueClicks;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("opens")
    @Getter
    @Setter
    private Object opens;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("uniqueOpens")
    @Getter
    @Setter
    private Object uniqueOpens;

    public AdvancedStatsClicksOpens() {
    }

    private AdvancedStatsClicksOpens(Builder builder) {
        this.clicks = builder.clicks;
        this.uniqueClicks = builder.uniqueClicks;
        this.opens = builder.opens;
        this.uniqueOpens = builder.uniqueOpens;
    }

    // Builder class for constructing object
    public static class Builder {
        private Object clicks;
        private Object uniqueClicks;
        private Object opens;
        private Object uniqueOpens;

        public Builder() {
        }

        public Builder clicks(Object clicks) {
            this.clicks = clicks;
            return this;
        }

        public Builder uniqueClicks(Object uniqueClicks) {
            this.uniqueClicks = uniqueClicks;
            return this;
        }

        public Builder opens(Object opens) {
            this.opens = opens;
            return this;
        }

        public Builder uniqueOpens(Object uniqueOpens) {
            this.uniqueOpens = uniqueOpens;
            return this;
        }

        public AdvancedStatsClicksOpens build() {
            return new AdvancedStatsClicksOpens(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", AdvancedStatsClicksOpens.class.getSimpleName() + "(", ")");
        if (clicks != null) joiner.add("clicks=" + clicks);
        if (uniqueClicks != null) joiner.add("uniqueClicks=" + uniqueClicks);
        if (opens != null) joiner.add("opens=" + opens);
        if (uniqueOpens != null) joiner.add("uniqueOpens=" + uniqueOpens);
        return joiner.toString();
    }

}
         
    
