/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Statistics API
 * The Twilio SendGrid Statistics API allows you to retrieve the various statistics related to your email program.  Tracking your emails is an important part of being a good sender and learning about how your users interact with your email. This includes everything from clicks and opens to looking at which browsers and mailbox providers your customers use.  SendGrid has broken up statistics in specific ways so that you can get at-a-glance data, as well as the details of how your email is being used.  Category statistics are available for the previous thirteen months only.  See [**Statistics Overview**](https://docs.sendgrid.com/ui/analytics-and-reporting/stats-overview) for more information.
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.stats.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.util.StringJoiner;


@ToString
public class CategoryStatsStatsInner {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("metrics")
    @Getter
    @Setter
    private CategoryStatsStatsInnerMetrics metrics;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("name")
    @Getter
    @Setter
    private String name;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("type")
    @Getter
    @Setter
    private String type;

    public CategoryStatsStatsInner() {
    }

    private CategoryStatsStatsInner(Builder builder) {
        this.metrics = builder.metrics;
        this.name = builder.name;
        this.type = builder.type;
    }

    // Builder class for constructing object
    public static class Builder {
        private CategoryStatsStatsInnerMetrics metrics;
        private String name;
        private String type;

        public Builder(String type) {
            this.type = type;
        }

        public Builder metrics(CategoryStatsStatsInnerMetrics metrics) {
            this.metrics = metrics;
            return this;
        }

        public Builder name(String name) {
            this.name = name;
            return this;
        }

        public CategoryStatsStatsInner build() {
            return new CategoryStatsStatsInner(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", CategoryStatsStatsInner.class.getSimpleName() + "(", ")");
        if (metrics != null) joiner.add("metrics=" + metrics);
        if (name != null) joiner.add("name=" + name);
        if (type != null) joiner.add("type=" + type);
        return joiner.toString();
    }

}
         
    
