/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid User API
 * The Twilio SendGrid User API allows you to modify the settings of a SendGrid user account such as the user's email address or username. Keeping your user profile up to date helps SendGrid verify who you are and share important communications with you.  See [**Account Details**](https://docs.sendgrid.com/ui/account-and-settings/account) for more information. You can also manage your user settings in the [SendGrid application user interface](https://app.sendgrid.com/account/details).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sendgrid.rest.api.v3.user.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.StringJoiner;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@ToString
public class UpdatePasswordRequest {

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("new_password")
    @Getter
    @Setter
    private String newPassword;

    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("old_password")
    @Getter
    @Setter
    private String oldPassword;

    public UpdatePasswordRequest() {}

    private UpdatePasswordRequest(Builder builder) {
        this.newPassword = builder.newPassword;
        this.oldPassword = builder.oldPassword;
    }

    // Builder class for constructing object
    public static class Builder {

        private String newPassword;
        private String oldPassword;

        public Builder(String newPassword, String oldPassword) {
            this.newPassword = newPassword;
            this.oldPassword = oldPassword;
        }

        public UpdatePasswordRequest build() {
            return new UpdatePasswordRequest(this);
        }
    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(
            ", ",
            UpdatePasswordRequest.class.getSimpleName() + "(",
            ")"
        );
        if (newPassword != null) joiner.add("newPassword=" + newPassword);
        if (oldPassword != null) joiner.add("oldPassword=" + oldPassword);
        return joiner.toString();
    }
}
