/*
 * This code was generated by
 *
 * SENDGRID-OAI-GENERATOR
 *
 * Twilio SendGrid Marketing Campaigns Lists API
 * The Twilio SendGrid Marketing Campaigns Lists API allows you to manage your contacts lists programmatically. Lists are static collections of Marketing Campaigns contacts. You can use this API to interact with the list objects themselves. To add contacts to a list, you must use the [Contacts API](https://docs.sendgrid.com/api-reference/contacts/).  You can also manage your lists using the Contacts menu in the [Marketing Campaigns application user interface](https://mc.sendgrid.com/contacts). For more information about lists and best practices for building them, see [**Building your Contact Lists**](https://sendgrid.com/docs/ui/managing-contacts/building-your-contact-list/).
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.sendgrid.rest.api.v3.mclists.models;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import java.math.BigDecimal;
import java.net.URI;
import java.util.StringJoiner;


@ToString
public class Metadata {
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("prev")
    @Getter
    @Setter
    private URI prev;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("self")
    @Getter
    @Setter
    private URI self;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("next")
    @Getter
    @Setter
    private URI next;
    @JsonInclude(JsonInclude.Include.NON_EMPTY)
    @JsonProperty("count")
    @Getter
    @Setter
    private BigDecimal count;

    public Metadata() {
    }

    private Metadata(Builder builder) {
        this.prev = builder.prev;
        this.self = builder.self;
        this.next = builder.next;
        this.count = builder.count;
    }

    // Builder class for constructing object
    public static class Builder {
        private URI prev;
        private URI self;
        private URI next;
        private BigDecimal count;

        public Builder() {
        }

        public Builder prev(URI prev) {
            this.prev = prev;
            return this;
        }

        public Builder self(URI self) {
            this.self = self;
            return this;
        }

        public Builder next(URI next) {
            this.next = next;
            return this;
        }

        public Builder count(BigDecimal count) {
            this.count = count;
            return this;
        }

        public Metadata build() {
            return new Metadata(this);
        }

    }

    @Override
    public String toString() {
        StringJoiner joiner = new StringJoiner(", ", Metadata.class.getSimpleName() + "(", ")");
        if (prev != null) joiner.add("prev=" + prev);
        if (self != null) joiner.add("self=" + self);
        if (next != null) joiner.add("next=" + next);
        if (count != null) joiner.add("count=" + count);
        return joiner.toString();
    }

}
         
    
